-- ============================================================
-- Esquema de Supabase para "Agenda de implementación MIND"
--
-- Cómo usarlo: en tu proyecto de Supabase ve a "SQL Editor" → "New
-- query", pega TODO este archivo y dale "Run". Es seguro volver a
-- correrlo (usa IF NOT EXISTS / DROP POLICY IF EXISTS donde aplica),
-- salvo las dos líneas finales de "ALTER PUBLICATION", ver nota ahí.
-- ============================================================

-- Necesaria para generar UUIDs con gen_random_uuid() (normalmente ya
-- viene habilitada en todo proyecto nuevo de Supabase).
create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- Tabla: capacitaciones (una fila = una sesión de capacitación)
-- Equivalente a la colección "capacitaciones" que antes vivía en
-- Firestore; mismos campos, con nombres de columna en snake_case.
-- ------------------------------------------------------------
create table if not exists public.capacitaciones (
  id              uuid primary key default gen_random_uuid(),
  udn             text not null,
  fase            text,                     -- "Fase 1" / "Fase 2" / "Fase 3"
  dia_id          text not null,            -- "dia1".."dia5"
  date            date not null,
  start_time      text not null,            -- hora de inicio, formato "HH:MM"
  duration        integer not null default 60,
  modalidad       text not null,            -- "Virtual (Teams)" / "Presencial"
  lugar           text,                     -- sala física o link de Teams
  objetivo        text,
  notas           text,
  modulos         text[] not null default '{}',
  roles           text[] not null default '{}',
  areas           text[] not null default '{}',
  implementadores text[] not null default '{}',
  hallazgos       jsonb not null default '[]',   -- [{ "fecha": "...", "texto": "..." }, ...]
  created_at      timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Tabla: catalog_items (UDN, Roles, Áreas, Módulos, Implementadores)
-- Equivalente al documento único "catalogos/main" de Firestore, pero
-- modelado como una fila por elemento (más natural en una base de
-- datos relacional): permite agregar/quitar un elemento con un solo
-- INSERT/DELETE, sin tener que leer y reescribir un arreglo completo.
-- ------------------------------------------------------------
create table if not exists public.catalog_items (
  id         bigint generated by default as identity primary key,
  kind       text not null check (kind in ('udn', 'roles', 'areas', 'modulos', 'implementadores')),
  value      text not null,
  created_at timestamptz not null default now()
);

-- Evita duplicados dentro del mismo catálogo sin importar mayúsculas/minúsculas
-- (refuerza en la base de datos la misma validación que ya hace la app).
create unique index if not exists catalog_items_kind_value_ci_idx
  on public.catalog_items (kind, lower(value));

-- ------------------------------------------------------------
-- Row Level Security
--
-- La app no usa cuentas de usuario: el acceso es solo por el link
-- compartido, usando la llave pública "anon" del proyecto (igual que
-- funcionaba antes con las reglas abiertas de Firestore). Por eso las
-- políticas de abajo permiten al rol "anon" hacer exactamente las
-- operaciones que la app necesita (leer/insertar/actualizar/borrar en
-- estas dos tablas) — ni una más. Esto es intencionalmente más
-- acotado que dejar la base de datos sin RLS (lo cual expondría TODA
-- la base por la API sin ningún control): aquí, en cambio, solo estas
-- dos tablas son accesibles, y solo con las operaciones aquí listadas.
--
-- Aun así, sigue siendo "cualquiera con el link puede editar todo".
-- Antes de compartir el link ampliamente, revisa la sección
-- "Seguridad" del README para ver cómo endurecer esto todavía más si
-- lo necesitas.
-- ------------------------------------------------------------
alter table public.capacitaciones enable row level security;
alter table public.catalog_items  enable row level security;

drop policy if exists "capacitaciones_select_anon" on public.capacitaciones;
drop policy if exists "capacitaciones_insert_anon" on public.capacitaciones;
drop policy if exists "capacitaciones_update_anon" on public.capacitaciones;
drop policy if exists "capacitaciones_delete_anon" on public.capacitaciones;

create policy "capacitaciones_select_anon" on public.capacitaciones
  for select to anon using (true);
create policy "capacitaciones_insert_anon" on public.capacitaciones
  for insert to anon with check (true);
create policy "capacitaciones_update_anon" on public.capacitaciones
  for update to anon using (true) with check (true);
create policy "capacitaciones_delete_anon" on public.capacitaciones
  for delete to anon using (true);

drop policy if exists "catalog_items_select_anon" on public.catalog_items;
drop policy if exists "catalog_items_insert_anon" on public.catalog_items;
drop policy if exists "catalog_items_delete_anon" on public.catalog_items;

create policy "catalog_items_select_anon" on public.catalog_items
  for select to anon using (true);
create policy "catalog_items_insert_anon" on public.catalog_items
  for insert to anon with check (true);
create policy "catalog_items_delete_anon" on public.catalog_items
  for delete to anon using (true);
-- Nota: a propósito NO se crea política de "update" para catalog_items,
-- porque la app nunca modifica un elemento existente, solo agrega o
-- quita — así esa operación queda bloqueada por completo, ni siquiera
-- para el rol "anon".

-- ------------------------------------------------------------
-- Tiempo real: agrega ambas tablas a la publicación que usa Supabase
-- Realtime, para que los cambios de una persona se reflejen en vivo
-- para todas las demás sin recargar la página.
--
-- Nota: si vuelves a correr este script y las tablas ya estaban
-- agregadas, estas dos líneas pueden marcar un error de tipo "ya
-- existe" — es inofensivo, ignóralo (o bórralas antes de re-ejecutar).
-- ------------------------------------------------------------
alter publication supabase_realtime add table public.capacitaciones;
alter publication supabase_realtime add table public.catalog_items;
